const Quotes = [
    "The only way to do great work is to love what you do.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "The future depends on what you do today.",
    "Education is the most powerful weapon you can use to change the world.",
    "Don't watch the clock; do what it does. Keep going.",
    "Your time is limited, so don't waste it living someone else's life.",
    "The only place where success comes before work is in the dictionary.",
    "Learn from yesterday, live for today, hope for tomorrow.",
    "Dream big and dare to fail.",
    "You are never too old to set another goal or to dream a new dream.",
    "The secret to getting ahead is getting started.",
    "You don't have to be great to start, but you have to start to be great.",
    "The road to success and the road to failure are almost exactly the same.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Success is not the result of spontaneous combustion. You must set yourself on fire.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Don't let what you cannot do interfere with what you can do.",
    "Believe you can and you're halfway there.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Your education is a dress rehearsal for a life that is yours to lead.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "The difference between ordinary and extraordinary is that little extra.",
    "Success is not in what you have, but who you are.",
    "The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
    "The expert in anything was once a beginner.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "The best way to predict the future is to create it.",
    "It's not about how bad you want it. It's about how hard you're willing to work for it.",
    "If you are not willing to learn, no one can help you. If you are determined to learn, no one can stop you.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "Your time is limited, don't waste it living someone else's life.",
    "Success is the sum of small efforts repeated day in and day out.",
    "The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
    "Don't count the days, make the days count.",
    "You are never too old to set another goal or to dream a new dream.",
    "Work hard in silence, let your success be the noise.",
    "The biggest risk is not taking any risk. In a world that is changing quickly, the only strategy that is guaranteed to fail is not taking risks.",
    "The only person you are destined to become is the person you decide to be.",
    "The best way to predict your future is to create it.",
    "You are never too old to set another goal or to dream a new dream.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Don't watch the clock; do what it does. Keep going.",
    "The only place where success comes before work is in the dictionary.",
    "Learn from yesterday, live for today, hope for tomorrow.",
    "Dream big and dare to fail.",
    "You don't have to be great to start, but you have to start to be great.",
    "The secret to getting ahead is getting started.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Believe you can and you're halfway there.",
    "The future belongs to those who believe in the beauty of their dreams."
  ];

  module.exports = Quotes;
  